-- ==================================================
-- QUESTION 1:
-- What is total revenue generated by Olist?
-- ==================================================

SELECT 
	ROUND(SUM(price), 2) AS 'Total Revenue Generated'
FROM olist_order_items_dataset;

-- ==================================================
-- FINDING
-- Total revenue generated: $13,591,643.70 
--
-- BUSINESS INTERPRETATION
-- Olist generated approximately $13.6 million in gross
-- merchandise revenue during the period convered by the dataset.
-- ==================================================


-- ==================================================
-- QUESTION 2:
-- How did monthly revenue change over time?
-- ==================================================

SELECT
	strftime('%Y-%m', o.order_purchase_timestamp) AS order_month,
	ROUND(SUM(oi.price), 2) AS monthly_revenue
FROM olist_orders_dataset o
JOIN olist_order_items_dataset oi
	ON o.order_id = oi.order_id
GROUP BY order_month
ORDER BY order_month;

-- ==================================================
-- FINDING
-- Revenue generally increased throughout the dataset
-- periodm with notable peaks during holiday seasons. 
--
-- BUSINESS INTERPRETATION
-- Olist generated approximately $13.6 million in gross
-- merchandise revenue during the period convered by the dataset.
-- ==================================================

























