-- ==================================================
-- QUESTION 1:
-- What is total revenue generated by Olist?
-- ==================================================
SELECT 
	ROUND(SUM(price), 2) AS 'Total Revenue Generated'
FROM olist_order_items_dataset;
-- ==================================================
-- FINDING
-- Total revenue generated: $13,591,643.70 
--
-- BUSINESS INTERPRETATION
-- Olist generated approximately $13.6 million in gross
-- merchandise revenue during the period convered by the dataset.
-- ==================================================


-- ==================================================
-- QUESTION 2:
-- How did monthly revenue change over time?
-- ==================================================
SELECT
	strftime('%Y-%m', o.order_purchase_timestamp) AS order_month,
	ROUND(SUM(oi.price), 2) AS monthly_revenue
FROM olist_orders_dataset o
JOIN olist_order_items_dataset oi
	ON o.order_id = oi.order_id
GROUP BY order_month
ORDER BY order_month;
-- ==================================================
-- FINDING
-- Monthly revenue increased substantially throughout 2017, growing from
-- $120,312.87 in January 2017 to a peak of $1,010,271.37 in November 2017.
--
-- Revenue remained relatively stable throughout most of 2018, generally
-- ranging between $850,000 and $1,000,000 per month. 
--
-- A significant revenue spike occured in November 2017, where sales
-- exceeded $1,000,000 for the first time in the dataset.
--
-- BUSINESS INTERPRETATION
-- The data suggests Olist experienced rapid business growth during 2017, 
-- followed by a period of stabilization in 2018. 
--
-- The sharp increase in revenue during November 2017 may be associated 
-- with seasonal shhopping events such as Black Friday, indicating that 
-- promotional periods can have a substantial impact on sales.
--
-- The relatively consistent revenue levels observed throughout 2018
-- suggest that Olist had established a larger and more stable customer
-- base compared with earlier periods. 
-- ==================================================

-- ==================================================
-- QUESTION 3:
-- Which product categories generate the most revenue?
-- ==================================================
SELECT 
	t.product_category_name_english,
	ROUND(SUM(oi.price), 2) AS total_revenue
FROM olist_order_items_dataset oi
JOIN olist_products_dataset p
	ON oi.product_id = p.product_id
JOIN product_category_name_translation t
	ON p.product_category_name = t.product_category_name
GROUP BY t.product_category_name_english
ORDER BY total_revenue DESC;
-- ==================================================
-- FINDING
-- Health & Beauty, Watches & Gifts, and Bed Bath & Table 
-- were the highest revenue-generating product categories.
--
-- Revenue appears concentrated among consumer lifestyle, home,
-- and gift-related products, which collectively account for 
-- a substantial portion of total sales.
--
-- BUSINESS INTERPRETATION
-- Customer demand appears strongest within personal care, home
-- living, and gift-oriented product categories. 
--
-- These categories may represent strategic opportunities
-- for targeted marketing campaigns, inventory expansion,
-- and customer retention initiatives. 
--
-- Understanding customer behavior within these high-revenue
-- categories could help Olist maximize future sales growth.
-- ==================================================

-- ==================================================
-- QUESTION 4:
-- Which states generate the most sales?
-- ==================================================
SELECT 
	c.customer_state,
	ROUND(SUM(oi.price), 2) AS total_sales
FROM olist_customers_dataset c
JOIN olist_orders_dataset o
	ON c.customer_id = o.customer_id
JOIN olist_order_items_dataset oi
	ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_sales DESC;
-- ==================================================
-- FINDING
-- States that brought Olist the highest sales are from 
-- the most populated 3 states, Sao Paulo, Rio de Janiero, 
-- and Minas Gerais. 
--
-- BUSINESS INTERPRETATION
-- Revenue is oconcentrated in a small number of highly
-- populated states. We also see that Olist's strongest
-- customer markets are located in Brazil's south-eastern
-- region. 
--
-- Maintaining customer acquisition and retention efforts
-- in these key markets is important. At the same time, 
-- lower-performing states may represent opportunities
-- for future growth through targeted marketing stratgies.
-- ==================================================























